PROGRAM LATRECORD;
USES WINCRT;

TYPE

REKAM=RECORD
NPM :STRING[15];
NAMA :STRING[35];
JENISKEL :CHAR;
TMP_LAHIR: STRING[30];
TGL_LAHIR : STRING[10];
AGAMA :STRING[25];
ALAMAT :STRING[100];
EMAIL :STRING[30];
HP :STRING[30];
END;

VAR

MAHASISWA:REKAM;

BEGIN

WRITELN('INPUT BIODATADATA MAHASISWA');
WRITELN('=================================');
WRITE('NPM          : ');READLN(MAHASISWA.NPM);
WRITE('NAMA         : ');READLN(MAHASISWA.NAMA);
WRITE('P/L          : ');READLN(MAHASISWA.JENISKEL);
WRITE('Tempat Lahir : ');READLN(MAHASISWA.TMP_LAHIR);
WRITE('Tanggal Lahir: ');READLN(MAHASISWA.TGL_LAHIR);
WRITE('AGAMA        : ');READLN(MAHASISWA.AGAMA);
WRITE('ALAMAT       : ');READLN(MAHASISWA.ALAMAT);
WRITE('EMAIL        : ');READLN(MAHASISWA.EMAIL);
WRITE('HP           : ');READLN(MAHASISWA.HP);

CLRSCR;

WRITELN('OUTPUT BIODATADATA MAHASISWA');
WRITELN('=================================');
WRITELN('NPM          : ',MAHASISWA.NPM);
WRITELN('NAMA         : ',MAHASISWA.NAMA);
WRITELN('P/L          : ',MAHASISWA.JENISKEL);
WRITELN('Tempat Lahir : ',MAHASISWA.TMP_LAHIR);
WRITELN('Tanggal Lahir: ',MAHASISWA.TGL_LAHIR);
WRITELN('AGAMA        : ',MAHASISWA.AGAMA);
WRITELN('ALAMAT       : ',MAHASISWA.ALAMAT);
WRITELN('EMAIL        : ',MAHASISWA.EMAIL);
WRITELN('HP           : ',MAHASISWA.HP);
END.
