PROGRAM INSERTION (INPUT,OUTPUT);
USES WINCRT;
CONST
MAX = 100;
VAR
A : ARRAY[1..MAX] OF INTEGER;
I, N : INTEGER;
PROCEDURE INSERTION_SORT;
VAR
I, POS : INTEGER;
NILAI : INTEGER;
TANDA : BOOLEAN;
BEGIN
FOR I := 2 TO N DO
BEGIN
NILAI := A[I];
POS := I;
TANDA := FALSE;
WHILE NOT TANDA DO
BEGIN
IF POS <= 1 THEN
TANDA := TRUE
ELSE IF NILAI >= A [POS-1] THEN
TANDA := TRUE
ELSE
BEGIN
A [POS] := A [POS-1];
POS:= POS-1
END
END; {WHILE}
A [POS] := NILAI;
END {FOR}
END;
BEGIN {MAIN}
WRITE ('MASUKAN BANYAK DATA (MAX=',MAX:2,'):');
READLN (N);
WRITELN ('MASUKAN ANGKA SEBANYAK ',N:1,':');
FOR I := 1 TO N DO
READ (A[I]);
INSERTION_SORT ;
FOR I := 1 TO N DO
WRITE (A[I]:1,' ');
READLN;
WRITELN;
READLN;
END.