PROGRAM MENAMBAH_ISI_FILE_STMIK;
USES WINCRT;
VAR
TIPEFILE:TEXT;
PESAN:STRING;

BEGIN
CLRSCR;

ASSIGN(TIPEFILE,'STMIK.TXT');
APPEND(TIPEFILE);
WRITELN(TIPEFILE,'MEMBANGUN KARIER BERKUALITAS');
WRITELN(TIPEFILE,'-----------------------------------------');

CLOSE(TIPEFILE);

END.