PROGRAM MENYUSUN_DERETAN_ANGKA_DENGAN_BINARY_TREE;
USES WINCRT;

TYPE
PTR = ^DATA;
DATA = RECORD
INFO: INTEGER;
LEFTSON,RIGHTSON: PTR;
END;

TYPE
ANGKAA = ARRAY [1..100]OF INTEGER;
VAR
BINARYTREE: PTR;

MENU : CHAR;
SELESAI : CHAR;
ANGKA : INTEGER;

{====================================}

PROCEDURE INORDER(BT: PTR);
BEGIN
     IF (BT <> NIL) THEN
     BEGIN
          INORDER(BT^.LEFTSON);
          WRITE(BT^.INFO:6);
          INORDER(BT^.RIGHTSON);
     END;
END;
{==================================}
PROCEDURE PREORDER(BT: PTR);
BEGIN
     IF (BT <> NIL) THEN
     BEGIN
          WRITE(BT^.INFO:6);
          PREORDER(BT^.LEFTSON);
          PREORDER(BT^.RIGHTSON);
     END;
END;
{================================}
PROCEDURE POSTORDER(BT: PTR);
BEGIN
     IF (BT <> NIL) THEN
     BEGIN
          POSTORDER(BT^.LEFTSON);
          POSTORDER(BT^.RIGHTSON);
          WRITE(BT^.INFO:6);
     END;
END;

{===============================}


PROCEDURE INSERT(VAR BT: PTR; INFO: INTEGER);
VAR
   BARU: PTR;
BEGIN
     IF (BT = NIL) THEN
BEGIN
     NEW(BARU);
     BARU^.INFO := INFO;
     BARU^.LEFTSON := NIL;
     BARU^.RIGHTSON := NIL;
     BT := BARU;
END
ELSE
IF (INFO <= BT^.INFO) THEN
   INSERT(BT^.LEFTSON, INFO)
ELSE
    INSERT(BT^.RIGHTSON, INFO);
END;

 {=============================}

PROCEDURE MENUUTAMA;
BEGIN
WRITELN('   MENYUSUN_DERETAN_ANGKA_DENGAN_BINARY_TREE   ');
WRITELN('===============================================');
WRITELN;
WRITELN('1. INPUT DATA !');
WRITELN('2. TAMPILKAN DATA SECARA IN ORDER');
WRITELN('3. TAMPILKAN DATA SECARA PRE ORDER');
WRITELN('4. TAMPILKAN DATA SECARA POST ORDER');
WRITELN('5. EXIT');

WRITELN;
WRITE('MASUKAN PILIHAN ANDA (1-5): ');
END;
{----------------------------------}

VAR I,N : INTEGER;
BEGIN
     WRITE('MASUKAN JUMLAH DATA DERETAN ANGKA !  :');READLN(N);
SELESAI:='N';
REPEAT
      CLRSCR;
      MENUUTAMA;
      READLN(MENU);
CASE MENU OF
'1' : BEGIN
CLRSCR;
FOR I := 1 TO N DO
BEGIN
WRITE('INPUT DATA KE ',I,' :');READLN(ANGKA);
INSERT(BINARYTREE,ANGKA);

END;
END;


'2' : BEGIN

WRITELN;
WRITELN('TAMPILKAN DERETAN ANGKA SECARA IN ORDER');
WRITELN;
WRITELN('=======================================');
WRITELN;
INORDER(BINARYTREE);
WRITELN;
END;
'3' :BEGIN

WRITELN;
WRITELN('TAMPILKAN DERETAN ANGKA SECARA PRE ORDER');
WRITELN;
WRITELN('========================================');
WRITELN;
PREORDER(BINARYTREE);
WRITELN;
END;
'4' : BEGIN

WRITELN;
WRITELN('TAMPILKAN DERETAN ANGKA SECARA POST ORDER');
WRITELN;
WRITELN('========================================');
WRITELN;
POSTORDER(BINARYTREE);
WRITELN;
END;

'5' :BEGIN
SELESAI:='Y';
END;
END;
READLN;
UNTIL (SELESAI='Y') OR (SELESAI='y');
END.

{sumber : lutfifebriandita.blogspot.co.id/2012/10/program-menyusunderetanangkadenganbinar.html}