PROGRAM SUWANDISHELLSORT;

USES
  WINCRT;

CONST
MAKS =10;
TYPE
LARIK =ARRAY[1..MAKS] OF INTEGER;
VAR
DATA : LARIK;
PROCEDURE INISIALISASI_DATA(VAR D : LARIK ; N : INTEGER);
VAR
I : INTEGER;
BEGIN
FOR I := 1 TO N DO
BEGIN
D[I] := RANDOM(99);
END;
END;
PROCEDURE TAMPIL_HASIL(HASIL : LARIK ; N : INTEGER);
 VAR
I : INTEGER;
BEGIN
FOR I:=1 TO N DO
BEGIN
WRITE(HASIL[I],' ');
END;
END;
PROCEDURE TUKAR_DATA(VAR DATA1,DATA2: INTEGER);
VAR
   BANTU : INTEGER;
   BEGIN
   BANTU := DATA1;
   DATA1:=DATA2;
   DATA2:=BANTU;
   END;

   PROCEDURE METODE_SHELLSORT(VAR A : LARIK; N : INTEGER);
   VAR
   I,J,JARAK : INTEGER;
   BEGIN
   JARAK:= N DIV 2;
   WHILE JARAK >0 DO
   BEGIN
   FOR I :=1 TO N - JARAK DO
   BEGIN
   J := I+JARAK;
   IF A[I]>A[J] THEN
   TUKAR_DATA(A[I],A[J])
   END;
   JARAK:=JARAK DIV 2
   END
   END;
   
BEGIN
  RANDOMIZE ;
  INISIALISASI_DATA (DATA,MAKS);
  WRITELN('DATA SEBELUM DI SORTING');
  TAMPIL_HASIL(DATA,MAKS);
  WRITELN;
  METODE_SHELLSORT(DATA,MAKS);
  WRITELN('HASIL SORTING METODE SHELL SORT');
  TAMPIL_HASIL(DATA,MAKS);
  READLN;
  END.
