PROGRAM QUEUE;
USES WINCRT;

CONST

MAX=3;

TYPE

A=ARRAY[1..MAX] OF STRING;

VAR

ANTRIAN:A;
NO_ANTRI:0..MAX;
TANYA:CHAR;

BEGIN
CLRSCR;

WRITELN('PROGRAM ANTRIAN SEDERHANA');
WRITELN('=========================');
TANYA:='Y';

WHILE TANYA IN ['Y','y'] DO

BEGIN
     WRITE('ELEMEN KE-1 = ');READLN(ANTRIAN[1]);
     NO_ANTRI:=NO_ANTRI+1;

     WRITE('ELEMEN KE-2 = ');READLN(ANTRIAN[2]);
     NO_ANTRI:=NO_ANTRI+1;

     WRITE('ELEMEN KE-3 = ');READLN(ANTRIAN[3]);
     NO_ANTRI:=NO_ANTRI+1;

     WRITELN;

     WRITELN('TAMPILAN = ',ANTRIAN[1],' ',ANTRIAN[2],' ',ANTRIAN[3]);
     WRITELN('JUMLAH ANTRIAN = ',NO_ANTRI);
     WRITELN('=========================');

     READLN;

     WRITE('AKAN TAMBAH DATA ? [Y/T]');READLN(TANYA);

     END;

WRITELN('JUMLAH ELEMEN DALAM ANTRIAN = ',NO_ANTRI);

READLN;

END.