PROGRAM TREESORT;
USES WINCRT;

TYPE
BTREE = ^SIMPUL;
SIMPUL = RECORD
ISI : CHAR;
KIRI,KANAN : BTREE;
END;

VAR ELEMEN : CHAR;
    P, ROOT, BARU : BTREE;

PROCEDURE SISIP(VAR ROOT,BARU : BTREE);
BEGIN
    BARU^.KIRI := NIL;
    BARU^.KANAN := NIL;

IF ROOT = NIL THEN
ROOT := BARU

ELSE
BEGIN
P := ROOT;

WHILE P <> NIL DO
BEGIN

IF BARU^.ISI < P^.ISI THEN
BEGIN

IF P^.KIRI <> NIL  THEN
P := P^.KIRI

ELSE
BEGIN
P^.KIRI := BARU;
P := NIL;

END;
END

ELSE
BEGIN

IF P^.KANAN <> NIL THEN
P := P^.KANAN

ELSE
BEGIN

P^.KANAN := BARU;
P :=  NIL

END;

END;
END;
END;
END;

PROCEDURE INORDER (ROOT : BTREE);
BEGIN
    IF ROOT <> NIL THEN
    BEGIN
        INORDER (ROOT^.KIRI);
        WRITE (ROOT^.ISI :4);
        INORDER (ROOT^.KANAN);
    END;
END;
PROCEDURE PREORDER (ROOT : BTREE);
BEGIN
    IF ROOT <> NIL THEN
    BEGIN
        WRITE (ROOT^.ISI :4);
        PREORDER (ROOT^.KIRI);
        PREORDER (ROOT^.KANAN);
    END;
END;

PROCEDURE POSTORDER (ROOT : BTREE);
BEGIN
  IF ROOT <> NIL THEN
   BEGIN
     POSTORDER (ROOT^.KIRI);
     POSTORDER (ROOT^.KANAN);
     WRITE (ROOT^.ISI : 4);
   END;
END;

BEGIN
CLRSCR;
WRITELN('TEKAN X JIKA SUDAH SELESAI MEMASUKAN DATA');
WRITE('MASUKAN DATA  : ');READLN(ELEMEN);
REPEAT                                         
    NEW (BARU);
    BARU^.ISI := ELEMEN;
    SISIP (ROOT,BARU);
WRITE('MASUKAN DATA  : ');READLN(ELEMEN);
UNTIL ELEMEN = 'x';
WRITELN;
WRITELN('===========================================');
WRITELN('               TREE SORT                 ');
WRITELN('===========================================');
WRITE('1. IN ORDER   : ');INORDER (ROOT); WRITELN;
WRITE('2. POST ORDER : ');POSTORDER (ROOT); WRITELN;
WRITE('3. PRE ORDER  : ');PREORDER (ROOT); WRITELN;
WRITE('===========================================');
READLN;
END.
