PROGRAM LATIHAN;
USES WINCRT;
VAR
VNAMA,VNPM,VKELAS,VJRS,VALAMAT,VHOBI:STRING;

BEGIN
WRITELN('INPUT BIODATA MAHASISWA');
WRITELN('=======================');
WRITE('NPM     : '); READLN(VNPM);
WRITE('NAMA    : '); READLN(VNAMA);
WRITE('KELAS   : '); READLN(VKELAS);
WRITE('JURUSAN : '); READLN(VJRS);
WRITE('ALAMAT  : '); READLN(VALAMAT);
WRITE('HOBI    : '); READLN(VHOBI);

CLRSCR;

WRITELN('BIODATA MAHASISWA');
WRITELN('=======================');
WRITELN('NPM     : ',VNPM);
WRITELN('NAMA    : ',VNAMA);
WRITELN('KELAS   : ',VKELAS);
WRITELN('JURUSAN : ',VJRS);
WRITELN('ALAMAT  : ',VALAMAT);
WRITELN('HOBI    : ',VHOBI);

END.